[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "GAMSPy Test"
authors = [{name = "Justine", email = "jbroihan@gams.com"}]
dynamic = ["version", "description"]
